language: node_js
node_js:
- '8'

install:
- yarn install

before_script:
- yarn p

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: true
  on:
    branch: master

