language: node_js
node_js:
- '8'

install:
- yarn install

before_script:
# build demo page
- yarn p

script:
# build lib
- yarn build
# test
- yarn test

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: true
  verbose: true
  on:
    branch: master

