language: node_js
node_js:
- '8'

install:
- yarn install

before_script:
# build demo page
- yarn p
# build source
- yarn build

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: true
  on:
    branch: master

